package com.nakamas.hatfieldbackend.models.enums;

public enum LogType {
    //TICKED
    CREATED_TICKET,
    MOVED_TICKET,
    UPDATED_TICKET,
    STARTED_TICKET,
    FINISHED_TICKET,
    COLLECTED_TICKET,
    //CATEGORY,
    CREATED_CATEGORY,
    UPDATED_CATEGORY,
    DELETED_CATEGORY,
    //INVENTORY ITEM
    ADD_NEW_ITEM_TO_INVENTORY,
    ADD_ITEM_TO_SHOPPING_LIST,
    USED_PART,
    UPDATE_ITEM_COUNT,
    UPDATE_ITEM,
    SCRAPPED_PART,
    REMOVE_ITEM_FROM_SHOPPING_LIST,
    //INVOICE,
    CREATED_SELL_INVOICE,
    CREATED_REPAIR_INVOICE,
    CREATED_BUY_INVOICE,
    CREATED_ACCESSORIES_INVOICE,
    INVALIDATED_INVOICE,
    //USER
    CREATED_WORKER,
    CREATED_CLIENT,
    UPDATED_USER,
    BANNED_USER,
    UNBANNED_USER,
    DELETED_USER,
    RESTORED_USER,
    //SHOP
    CREATED_SHOP,
    ITEM_MARKED_DEFECTIVE, UPDATED_SHOP
}
