# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java Build with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'corretto'
        
    - name: Make Gradlew Executable
      run: chmod +x ./gradlew
      
    - name: Run tests
      run: |
        ./gradlew check
        
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2.2.0
      with:
        junit_files: 'build/test-results/test/*.xml'
        
    - name: Export Spring Endpoints
      uses: idealo/spring-endpoint-exporter-action@v1.0.11
      with:
        input-path: ./build/libs/HatfieldBackend-0.0.1-SNAPSHOT.jar
        output-path: ./documentation.json
        include-filters: com.nakamas.hatfieldbackend.*
        
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: documentation_yaml
        path: ./documentation.json
        retention-days: 5
